export const numbers_operators = [
    {val : "C", str : "clear"},
    {val : "<", str : "remove"},
    {val : "7", str : "seven"},
    {val : "8", str : "eight"},
    {val : "9", str : "nine"},
    {val : "/", str : "divide"},
    {val : "4", str : "four"},
    {val : "5", str : "five"},
    {val : "6", str : "six"},
    {val : "*", str : "multiply"},
    {val : "1", str : "one"},
    {val : "2", str : "two"},
    {val : "3", str : "three"},
    {val : "-", str : "subtract"},
    {val : ".", str : "decimal"},
    {val : "0", str : "zero"},
    {val : "=", str : "equals"},
    {val : "+", str : "add"},
];
